<?php
############################################################################################################
# Software: Regimed                                                                                        #
#(Registro de Medios Informáticos)     					                                		           #
# Version:  3.0.1                                                     				                       #
# Fecha:    01/06/2016 - 03/04/2018                                             					       #
# Autores:  Ing. Manuel de Jesús Núñez Guerra   								     			           #
#          	Msc. Carlos Pollan Estrada											         		           #
# Licencia: Freeware                                                				                       #
#                                                                       			                       #
# Usted puede usar y modificar este software si asi lo desea, pero debe mencionarr la fuente               #
############################################################################################################

//// a
$clickmas = "Click en (+) para generar nuevos Talones de Sellos";
$daleclik="Click para ver Notificaciones...";
$nohay="No existen Notificaciones.";
$actual ="Fichero Actual";
$nuevsello = "Seleccione Nuevo Sello";
$arrastrar0 = "Arrastre el fichero en el &aacute;rea sombreada, o <b>click para cargarlo al &aacute;rea de texto</b>";
$arrastrar = "Arrastre el fichero en el &aacute;rea sombreada, o <b>click para seleccionarlo</b>";
$arrastrar1= "Arrastre el fichero aqu&iacute;";
$arrastrar2= "Su&eacute;ltelo aqu&iacute;!";
$arrastrar3= "API del fichero no soportado para este navegador";
$arrastrar4= '<font color="red">ERROR.</font> Extensi&oacute;n no soportada, solo se aceptan .zip y .sql. Por favor trate de nuevo!';
$arrastrar5= "<span><font color=\'#000000\'>Fichero cargado!</font></span>";
$ajax2 = '<p style="font-size: 10px;">Seleccione su nombre de Usuario, si no est&aacute; registrado por favor reg&iacute;strese!</p>
<p style="font-size: 10px;">Si no desea registrarse, y solo desea realizar consultas, puede escoger de la lista al usuario <b>Invitado</b></p>
<p style="font-size: 10px;">Son considerados usuarios de este sitio, solo aquellos que tengas AFT bajo su custodia</p>';
$ajax = '<p style="font-size: 10px;">La contrase&ntilde;a debe tener <b>Entre 6 - 20 caracteres</b> de longitud</p>
<p style="font-size: 10px;">Debe contener al menos <b>una letra</b></p>
<p style="font-size: 10px;">Debe contener al menos <b>un n&uacute;mero</b></p>
<p style="font-size: 10px;">La contrase&ntilde;a <b>no puede</b> contener <b>caracteres speciales</b> (@, %, etc)</p>
<p style="font-size: 10px;">No debe ser la misma que el ID del Usuario</p>
<p style="font-size: 10px;">La validaci&oacute;n es <b>Sensible</b></span></p>';
$accesositio = 'CONTROL DE ACCESO';
$btAprueba = "Aprueba DT.";
$btlistacust="LISTA DE CUSTODIOS";
$btmanual="Manual de Usuario";
$no_traspasos = "Este medio no ha tenido traspasos";
$no_upgrade = "Este medio no ha tenido upgrade";
$record = "Historial de traspasos";

//// B
$btversion = "Registro de Medios Inform&aacute;ticos";
$btversion1 = "Medios Inform&aacute;ticos";
$btversion2 = "Registro de Medios Inform&aacute;ticos";
$btversion3 = "Actualizado";
$derechos   = 'Este Sitio Web es un Software Libre con (<a href="installation/gpl.html" target="_blank">licencia de GNU/GPL</a>). ';
$btaceptar = 'Aceptar';
$btcancelar = 'Cancelar';
$bteditar = 'Editar';
$bteliminar = 'Eliminar';
$btinsertar = 'Insertar';
$claveacceso = 'Introduce tu clave de acceso';
$datosincorrectos = 'Datos Incorrectos';
$btusuario ='Usuario';
$btusuario1 ='Usuario';
$Invitado = 'Invitado';
$btpassw = 'Contrase&ntilde;a';
$btpassw1 = 'Claves';
$btpassw2 = 'Clave del Administrador';
$olvidapassw = 'Olvid&eacute; mi Contrase&ntilde;a';
$Ucumpleregla= 'El Usuario debe cumplir estas reglas';
$Pcumpleregla= 'La contrase&ntilde;a debe cumplir estas reglas';
$btSeguridad = 'Seguridad';
$btver = 'Ir';
$cantidadmost = "Registros a Mostar";
$btregisusuario ="REGISTRO DE USUARIOS";
$bttextobuscar ="Escriba el texto a buscar";
$btrecords = "Registros";
$btpage = 'P&aacute;gina';
$bthome = 'Inicio';
$btpmtto = 'Plan de Mantenimiento';
$btpmtto1 = 'PLAN DE MANTENIMIENTO';
$btpmtto2 = 'Mantenimiento';
$btprep = 'Plan de Reparaciones';
$btprep1 = 'PLAN DE REPARACIONES';
$btprep2 = 'Reparaciones';
$bttrasp = 'Traspasos';
$bttrasp2 = 'Traspasar';
$btbajas = 'Bajas';
$btbaja = 'Baja';

$btbajas1 = 'dar Baja';
$bthmtas = 'Herramientas';
$btsearch = 'B&uacute;squedas';
$btinsp = 'Registro de Inspecciones';
$btinsp1 = ' Inspecciones';
$btlegal = 'Base Legal';
$btvisita = 'Visita';
$btvisitas = 'Visitas';
$btayuda = 'Ayuda';
$btacerca = 'Acerca de';
$bttipo = 'Tipo';
$remplazado_por = "Remplazado por";
$pcescritorio ='PC Escritorio';
$pcportatil = 'Port&aacute;tiles';
$pccliente = 'Clientes Ligeros';
$pcservidor ='Servidores';
$pcservidorNAS ='Servidores NAS';
$fotocopia ='Fotocopiadoras';
$tubo ='Tubo Cat&oacute;dico';
$btmostrartodo ='Mostrar Todo';
$btmostrartodo1 ='Mostrar todas las Unidades';
$enero='Enero';
$febrero='Febrero';
$marzo='Marzo';
$abril='Abril';
$mayo='Mayo';
$junio='Junio';
$julio='Julio';
$agosto='Agosto';
$septiembre='Septiembre';
$octubre='Octubre';
$noviembre='Noviembre';
$diciembre='Diciembre';
$btano = "A&ntilde;o";
$btmes = "Mes";
$btrestaurar ="Restaurar";
$btterminar ='Terminar';
$btborradict = 'Eliminar Dictamen';
$Codificadores ='Codificadores';
$Preferencias ='Preferencias Avanzadas';
$Opciones ='Datos de las Entidades';
$Memorias ='Medios Extraibles';
$Memorias1 ='MEMORIA RAM';
$btpanel='Panel de Control';
$btcontrol='Control de Acceso';
$btregmedio='Registro de Medios';
$btregmedio1='Medio';
$btAreas='&Aacute;REAS';
$btAreas1='&Aacute;REA';
$btAreas4=' en el &Aacute;REA: ';
$btAreas2='&Aacute;REA';
$btcategmedios='Categor&iacute;as de Medios';
$btcategmedios1='Categor&iacute;a';
$btcategmedios2='CATEGOR&Iacute;A';
$btcategmedios3='CATEGOR�A';
$btClaves='Claves';
$btcreasalva='Realizar Salvas de la Base de Datos al Salir de la Aplicaci&oacute;n';
$btrecur='Recordar contrase&ntilde;a';
$btconserva='Conservar &Uacute;ltima B&uacute;squeda';
$btvis='Registros a Mostrar';
$btcolumnas = 'Columnas';
$btsalvas='Realizar salva a la Base de Datos';
$recomendable='Tenga en cuenta que esta opci&oacute;n es irreversible; una vez fusionadas las unidades, no podr&aacute; volver atr&aacute;s. <br>Es RECOMENDABLE mantener activado: ';
$btdatabase='Base de Datos';
$btCustodios="Custodio";
$btCustodios1="Custodios";
$btResoluciones ='Disposiciones Legales';
$btManuales='Manuales';
$btImportar='Importar';
$btExportar='Exportar';
$btbtecnicas='Historial de Bajas';
$repara='Optimizar Base Datos';
$btregmemorias='REGISTRO DE MEMORIAS USB';
$DESCRIPCION='DESCRIPCI&Oacute;N';
$DESCRIPCION1='Descripci&oacute;n';
$DESCRIPCION2='DESCRIPCI&Oacute;N';
$btMARCA='MARCA';
$CUSTODIO="CUSTODIO";
$btnoregistro='No existen registros';
$btdatosentidad='Datos de la Entidad';
$btdatosentidad1='Medios de la Entidad';
$btdatosentidad2="Entidades";
$btdatosentidad3="ENTIDAD";
$btdatosentidad4="Entidad Receptora";
$masvivistas="Existen m&aacute;s de 30 visitas registradas.";

$btNombre='Nombre';
$SITIO='SITIO WEB';
$SITIO1='Sitio Web';
$btmensaje='Servicio de Mensajer&iacute;a';
$Inicializacion='Inicializaci&oacute;n';
$btnota='<b>Nota:</b> La Opci&oacute;n de inicializaci&oacute;n solo se realizar&aacute; cuando se ha tenido la certeza de que los datos primarios introducidos en este sitio est&aacute;n errados y se desea que la aplicaci&oacute;n se inicialice para recomenzar';
$restart='Inicializar Sistema';
$Inicializar='Inicializar';
$save='Guardar Preferencias';
$Opcion='Opcion';
$msgoptim = 'La Tabla -%s- ha sido optimizada';
$msgoptim1 = 'Las Tablas han sido optimizadas';
$btcargando='Cargando la P&aacute;gina ... Espere por favor';
$bttitulo='Sitio Web - Seguridad Inform&aacute;tica -';
$logout ='Salir';
$logout1 ='Salir de la Aplicaci&oacute;n';
$Calcular='Calcular';
$Totalizar='Totalizar';
$TOTALES ='TOTALES';
$bttotalreg='Total de Registros';
$DEL =" del ";
$btidiomes ="Espa&ntilde;ol";
$btidiomen ="Ingl&eacute;s";
$recuperacla='Recuperar Clave';
$btnota2='Se le har&aacute; llegar un email con sus datos personales.';
$sol_registr3 ='Solicitud de Clave';
$btestado="Estado";
$btRealizado="Realizado";
$btRealizado1=" ha realizado ";
$btPendiente = "Pendiente";
$btPLANIFICADOR="PLANIFICADOR";
$btPLANIFICADOR1="PLANIFICAR PARA";
$btInventario="Inventario";
$btCRONOGRAMA="CRONOGRAMA";
$btAREASRES = '&Aacute;REAS DE RESPONSABILIDAD';
$bttmecateg="Total Medios seg&uacute;n Categor&iacute;as";
$bttmecateg1="Total Medios";
$bttmecateg2="Total Perif&eacute;rifos y Accesorios";
$btSELLO="SELLO";
$btgensello="Sellos";
$btMODELO='MODELO';
$btEN = ' en ';
$btEN1 = ' en ';
$btPERTENECE='PERTENECE AL ';
$btPERTENECE1='Usuario perteneciante a la Entidad:  ';
$btOBSERVACIONES='OBSERVACIONES';
$btsalvare='Salvas Realizadas';
$btORIGEN='ORIGEN';
$btDESTINO='DESTINO';
$btDESTINO1='DESTINO FINAL DE LAS BAJAS';
$btDESTINO2='DESTINO FINAL';
$btActivo="Activo";
$btRoto="Roto";
$btTaller='Taller Reparaciones.';
$btEXPEDIENTE="EXPEDIENTE";
$btEXPEDIENTE1="Expediente T&eacute;cnico";
$btPLACA="PLACA";
$bttargeta='TARGETA GR&Aacute;FICA';
$btRED="RED";
$btFUENTE="FUENTE";
$btSONIDO="SONIDO";
$btdevice="LECTOR/RW/HDD";
$Hombre="Hombre";
$Mujer="Mujer";
$btnCargo='Cargo';
$scri_imp5="El Login: <b>-%s-</b> ya existe. Por favor vuelve a intentarlo";
$scri_imp6="El Usuario: <b>-%s-</b> ya existe. Por favor vuelve a intentarlo";
$scri_imp7="El C&oacute;digo: <b>-%s-</b> ya existe. Por favor chequ&eacute;elo";
$btCampo="Campo";
$btValor="Valor";
$hoja_calX = "Hoja de C&aacute;lculo";
$bteditaunid='Editar Entidades';
$btAanterior="&Aacute;rea Anterior";
$btAdestino ="&Aacute;rea Destino";
$btlimpiar="Limpiar";
$btBuscadorGeneral="Buscador General";
$btotros='OTROS PERIF&Eacute;RICOS Y ACCESORIOS';
$btotrosComp='OTROS COMPONENTES DEL AFT';
$Comp='COMPONENTES DEL AFT';
$comp_m ="COMPONENTE";
$historial='HISTORIAL DE CAMBIOS DE HARDWARE';
$btSistema="Sistema";
$btnomedio="<b>%s</b> no tiene PC bajo su custodia";
$btnomedio1="<b>%s</b> ya tiene definido en <font color='red'>%s</font> sus Claves de Acceso";
$btoptimizar ="Optimizar";
$btrepara = "Reparar";
$repara1 = 'La Tabla -%s- ha sido Reparada';
$repara2 = 'Las Tablas han sido Reparadas';
$IRa = "Ir a la p&aacute;gina: ";
$btListado="LISTADO DE MEDIOS TILDADOS COMO DEFECTUOSOS";
$btListado1="Medios Defectuosos";
$btRESULTADOS="RESULTADOS";
$btspera = "Por favor espere a que termine el proceso de Exportaci&oacute;n";
$btestimado="Estimado %s, adjunto le enviamos los datos solicitados.\n\nCon toda consideraci�n\n\n";
$btequipo = "Equipo Desarrollador ";
$btselectenti ='Seleccione la Entidad';
$btACTIVOS="ACTIVOS";
$otrosdet="Otros detalles del Medio";
$otrosdet1="Otros Medios";
$otrosdet2="Todas las Entidades";
$otrosdet3="Detalles de la Exportaci&oacute;n";
$mensajex ="La versi&oacute;n de la Base de Datos que desea restaurar no corrresponde a la versi&oacute;n 2.0";
$btdict="DICTAMEN T&Eacute;CNICO";
$btDesea="&iquest;Desea eliminar Visitas?";
$btCantid="Cantidad a eliminar";
/////////////
//A
$btacuerdo ="Estoy de acuerdo";
$ase = "Ascendente";
$ase1 = "Descendente";
$aclara ='(La informaci&oacute;n solicitada y marcada en <font color="#FF0000">ROJO</font>, es de car&aacute;cter obligatorio)';
$advierte = 'Mensaje de Advertencia.';
$message1 = "Se han restaurado satisfactoriamente  los datos con el Ficheo de Salva: <font color='red' size='2'><b>";
$message2 = "Se ha restaurado la Base de Datos <b>-";
$message3 = " con la salva realizada el ";

$apodo = "El nombre: ";
$mess1 =" y/o el email introducido: ";
$mess2 ="no tienen coincidencia en la Base de Datos";
$mess3 ="Intentar de Nuevo";
$mess4 ="El correo no ha sido enviado. Por favor Verifique los datos de su conexi&oacute;n";
$mess5 ="Se ha enviado satisfactoriamente un correo con sus Datos Personales a:";
$mess6="Ir al ";
$apodo1 = "Nombre";
$apodo2 = "Nick";
$no_addres = "Direcci&oacute;n de E-Mail no v&aacute;lida";
$al =' al ';

//C
$clave ='Contrase&ntilde;a ';
$clave1 ='Repetir Contrase&ntilde;a ';
$clave2 ='Contrase&ntilde;a Incorrecta. Por favor intente de nuevo';
$clave3='Host, Usuario y/o Clave del Servidor MySQL incorrectos';
$claveolvida ='&iquest;Olvidaste tu Contrase&ntilde;a?';
$cerrar= "CERRAR SESI&Oacute;N";
$cerrar1= "Finalizar la  Sesi&oacute;n";
$cerrar2= "Cerrar...";
$contra = "La contrase&ntilde;a no coincide con su repetici&oacute;n";
$contra1 = "el campo en donde se repite la Contrase&ntilde;a";
$contra2 = "Contrase&ntilde;a";
$cuidado ="Realmente desea eliminar el Registro?. Una vez eliminado los registros asociados a este no se pueden recuperar";
$cuidado1 ="Realmente desea eliminar el Registro?. Una vez eliminado no se puede recuperar";
$cuidado2 ="Realmente desea continuar con el proceso de Baja ?.";
$cargar ='CARGAR SCRIPT .sql';
$cargar1 =' SCRIPT .sql';
$cargar2 ="Subir";
$cr_exel = 'Crear EXEL';
$cr_pdf = 'Crear PDF';
$cr_filtro = 'Crear Consulta';
$cr_pdf1 = 'Usted a seleccionado ';
$combo ='Seleccionar Todos';
$combo1 ='Seleccionar';
$cleckcrea=" para crearlo";
$btcertifica="Por favor, es necesaria la Certificaci&oacute;n.";
$btcertifica1="Certificaci&oacute;n";
$btcertifica2="CERTIFICACI&Oacute;N";
$btconformado="Este Medio no tiene Expediente conformado";
$btCreate="Crear";
//D
$dir ='Direcci&oacute;n';
$dir1 = "Direcci&oacute;n IP";
$dir2 = "DIRECCI&Oacute;N IP";
$de =' de ';
$De ='De ';
$dbase = "Base de Datos";
$desde ='De';
$datosdelamin="Datos del Administrador de la Entidad";
//E
$ellos ='De ellos';
$e_mail ='Direcci&oacute;n Electr&oacute;nica ';
$enviasenala ='Enviar';
$electron ='Correo Electr&oacute;nico';
$electron1 ='Correo Electronico';
$electron2 ='E-Mail';
$exit =' SALIR ';
$eliminamarca ='Eliminar Marcados';
$edocu1 ='RESULTADO DE LA B&Uacute;SQUEDA';
$edocu2 ='Resultado de la b&uacute;squeda';
$e_i = "(es/in)";
$enco_user ="USUARIOS ENCONTRADOS";
$estructra2 ='Datos';
$estructra3 ='Estructura';
$estructra4 ='y';
$bteliminado="El fichero <b>-%s-</b>, ha sido Eliminado";
$exte ='La Base de Datos ';
$exte2 =' existe.';
$exte3 ='El Login ';
$exte4 =' Por favor, escoja otro.';
$exptr ='Exportar';
$edita ='Editar';
$en_la =' en la ';
$errorr3 ="El nombre de esa imagen ya existe";
$el_los = " el o los ";
$motor = "Motor";

//F
$forreg ='Formulario de Registro';
$Fecha ='Fecha';
$falt = "Falta el campo ";
$fot ="Im&aacute;gen";
$foto ="Imagen";
$foto1 ="Im&aacute;genes registradas";
$filtr ='Filtrar';
$filtr1 ='Filtrar por';

//G
$guest_con ='Invitados';
$guest_con1 ='En L&iacute;nea';
$gnrar ='Generar';

//H
$home_pagge ='P&aacute;gina de inicio del Portal';
$hasta ='Hasta';
$home =' Inicio ';
$h_oficial = ", son las ";
$h_hora ="Hora";

//I
$idioma ='Seleccione el Idioma';
$idi_es ='Espa&ntilde;ol';
$idi_en ='Ingl&eacute;s';
$inf1 = "Es la palabra clave que, junto con el identificador, corrobora que la persona que accede al sistema se identifica con los datos proporcionados en este registro";
$inf2 = "El nombre de usuario o LOGIN constituye su identificador en nuestro sistema. Sera necesario que proporcione su identificador y clave para tener acceso a todo el sistema y realizar solicitudes documentales";
$inf3 = "Proporcione una direccion electronica valida. A esta direccion seran enviados los datos de su registro asi como toda la informacion que solicite via email.";
$inf4 = "Informaci&oacute;n sobre el Fondo";
$in_name = "Nombre de la Instituci&oacute;n";
$impo_exp1 ="Importar Datos";
$impo_exp2 ="Exportar Datos";
$impo_exp3 ="Importar Script";
$impo_exp4 ="Exportar Script";
$impo_exp5 ="Gesti&oacute;n de Base de Datos";
$impo_exp6 ='Exportar Datos';
$impo_exp7 ='Exportar una o m&aacute;s Tablas';
$impo_exp8 ='Importar';
$impo_exp9 ='Exportar';
$impo_exp10 ='Importando Script...';
$Ir ="Ir";

//L
$languag = 'Idioma';
$ligpl = "LICENCIA GNU/GPL";
$ligpl1 = "Licencia bajo la cual est&aacute; registrada este Software";
$LA=" la ";

//M
$musuario1 ='Modificar Usuario ';
$mregtr ='Modificar Registro';
$marcar ='Marcar para';
$modificas1 = 'Modificar Datos';
$modificas2 = 'Modificar Datos del Usuario';
$month = "Mes";
$mostrar ='Registros a mostrar: ';
$mostrar1 ='Registros';
$mostrar2 ='Mostrar Encabezado';
$mostrar3 ='Mostrar Pie de P&aacute;gina';
$mostrar4 ='Mostrar No. Orden';
$mostrar5 ='Comenzar por: ';
$mostrar6 ='Mostrar';
$m_r_Greeting = "Estimado(a): ";
$m_Thanks = "Con toda consideracion, ";
$m_Signature = "Servicios Tecnicos Industriales.\nComandante Manuel Fajardo RiVero.\nCuba.";

//N
$new ='Nuevo Usuario';
$new1 ='Nuevo Usuario';
$new2 ='Nueva ';
$new3 ='Nuevo ';
$new4 ='Nuevo';
$new6 ='Usuarios';
$newreg ='INICIAR SESI&Oacute;N';
$nombreapell ='Nombre y Apellidos: ';
$nombreapel2 ='N. Apellidos: ';
$nick ='Login';
$nick1 ='Login del Administrador';
$noregitro ='No existen Registros en esta Base de Datos';
$noregitro1 ='No existen Registros en esta Tabla';
$noregitro2 ='No existen Usuarios Registrados';
$noregitro3 ='No existen ';
$noopina ='No existen opiniones emitidas ';
$noart ='No existen Resoluciones Publicadas';
$noche ='Buenas noches ';
$nopertenece ='Usted no pertenece al Grupo de Administradores.<br>S&oacute;lo a la Gesti&oacute;n Documental.';
$nopertenece1 ='Usted no pertenece al Grupo de Administradores.<br>S&oacute;lo a la Gesti&oacute;n Documental. Si desea cambiar sus datos, p&oacute;ngase en contacto con el WebMaster.';
$newmess ='Nuevo Mensaje';
$n_fich = "El fichrero -requires/configguracion.php-<br>no existe o est&aacute; da&ntilde;ado, por favor verif&iacute;quelo o de click en -Instalar-";
$no_log = "Esta &Aacute;rea no tiene medios inform&aacute;ticos";
$si_log = "LOGO ACTUAL DEL";
$no_completo ="Usted no ha completado el proceso de Registro.\nPor favor revice su Mensajer&iacute;a o p&oacute;ngase\nen contacto con el Administrador del Portal";
$no_insert ="INSERCI&Oacute;N CANCELADA";
$no_accion ="ACCI&Oacute;N CANCELADA";
$no_registrado = "Usted no se ha registrado, por favor h&aacute;galo";
$no_result ="La B&uacute;squeda no arroj&oacute; ning&uacute;n resultado.";
$no_result0 ="La B&uacute;squeda no arroj&oacute; ning&uacute;n resultado.";
$no_result1 ="La B&uacute;squeda no arroj&oacute; ning&uacute;n resultado.<br>Usted puede realizar una Nueva <a href='frmsubFondo.php'>B&uacute;squeda</a>";
$no_result2 ="La B&uacute;squeda no arroj&oacute; ning&uacute;n resultado.<br>Usted puede realizar una Nueva <a href='frmSerie.php'>B&uacute;squeda</a> o <a href='nueva_serie.php'>Crear</a> una nueva.";
$no_result3 ="La B&uacute;squeda no arroj&oacute; ning&uacute;n resultado.<br>Usted puede realizar una Nueva <a href='frmSerie.php'>B&uacute;squeda</a>.";
$no_result4 ="La B&uacute;squeda no arroj&oacute; ning&uacute;n resultado.<br>Usted puede realizar una Nueva <a href='frmefem.php'>B&uacute;squeda</a>";
$no_result5 ="La B&uacute;squeda no arroj&oacute; ning&uacute;n resultado.<br>Usted puede realizar una Nueva <a href='frmDocumento.php'>B&uacute;squeda</a>";
$no_result6 ="La B&uacute;squeda no arroj&oacute; ning&uacute;n resultado.<br>Usted puede realizar una Nueva <a href='frmDocumento.php'>B&uacute;squeda</a> o <a href='nuevo_doc.php'>Crear</a> una nueva.";
$no_result7 ="La B&uacute;squeda no arroj&oacute; ning&uacute;n resultado.<br>Usted puede realizar una Nueva <a href='frmmateria.php'>B&uacute;squeda</a>";
$no_result8 ="La B&uacute;squeda no arroj&oacute; ning&uacute;n resultado.<br>Usted puede realizar una Nueva <a href='frmsubSerie.php'>B&uacute;squeda</a>.";
$no_result9 ="La B&uacute;squeda no arroj&oacute; ning&uacute;n resultado.<br>Usted puede realizar una Nueva <a href='frmsubSerie.php'>B&uacute;squeda</a> o <a href='nueva_subserie.php'>Crear</a> una nueva.";
$no_scr ="No puede ser escrito";
$no_scr1 ='El fichero ';
$not ="Nota";
$n_entidad="Nueva Entidad";
$name_ser ="Nombre del servidor";
$name_use ="Nombre del Usuario de la Base de Datos, usualmente -<b>root</b>-";
$name_use1 ="El nombre del usuario te tiene que haber estado facilitado cuando has creado la base de datos o bien te la tiene que facilitar tu ISP, Usualmente -<b>root</b>-";
$name_ndb ="Nombre de la nueva base de datos";
$name_ndb1 ="Algunos servidores s&oacute;lo permiten un n&uacute;mero limitado de bases de datos por sitio Web.";
$name_ndb2 ="Crear una r&eacute;plica de la Base de Datos";
$name_pas = "Contrase&ntilde;a del Servidor MySQL";
$name_pas1 ="Por seguridad se recomienda una contrase&ntilde;a para el Servidor MySql";
$name_ws ="Escriba el Nombre del Sitio Web";
$name_ws1 ="Escribe el nombre de tu Sitio Web. Este nombre se usar&aacute; en los correos que envies, escribe algo significativo.";
$name_ws2 ="Ejemplo: Mi Sitio Web.";
$name_ws3 ="Nombre del Sitio Web";
$no_deta ='Los detalles de la base de datos son incorrectos y/o estan vacios.';
$name_admin ='Nombre del Administrador';
$no_escrito ='El archivo de configuraci&oacute;n y/o el directorio no puede ser escrito, o bien, se ha producido un error de escritura en el archivo de configuraci&oacute;n. Tendr&aacute;s que a&ntilde;adir el siguiente fragmento de codigo manualmente en el archivo <b>requires/configuracion.php</stron> (si no existe, cr&eacute;alo). Haz click para seleccionar el texto.';
$n_menu ='NUEVO MEN&Uacute;';
$norma11 ='Norma Usada';
$notif = 'Notificacion de Registro';
$n_mail = 'Lo sentimos. Su Correo no ha sido enviado. Verifique la configuracion de su correo o contacte al WebMaster';
$n_mail1 = 'Su Correo ha sido enviado';
$no_ext ='Extension No Soportada';
$nueva_con ="Nueva B&uacute;squeda";
$no_ima =' el fichero seleccionado para el Logo no es una imagen o ese formato no es aceptado.\r\nSolo se aceptan las extensiones: JPG, GIF, PNG y BMP.';
$no_ima1 =' el formato del fichero seleccionado no es aceptado.\r\nSolo se aceptan las extensiones: ';
$no_ima2 = "Seleccione el Logotipo de su Instituci&oacute;n";
$no_ima3 = "Usted puede agregar el Logotipo desde el M&oacute;dulo de Administraci&oacute;n.";
$no_ima4 = "El peso de Fichero seleccionado es mayorque que el permitido. Este no se adjuntara.";
$nomb_tbla = "Nombre de la Tabla";
$nume_campos = "No. de campos";
$no_elimina ="Esta Tabla no puede ser Eliminada";
$no_vaciada ="Esta Tabla no puede ser Vaciada";
$nom_ext_im = "Nombre y Ext. de la Imagen";
$ngina="Nombre de la P&aacute;gina";
$btnotabaja="Para culminar el proceso de Baja, es necesario adjuntar el documento que certifica el destino final";

//O
$btorganoemi="&Oacute;rgano Emisor";
$btorganoemi2="&Oacute;RGANO EMISOR";
$opin ='OPINI&Oacute;N ';
$opin1 = 'Opinar';
$opi = "su criterio sobre el Portal";
$organ = "Organizaci&oacute;n";
$optimi = "La Base de Datos ha sido Optimizada";
$optimi1 = "Optimizar Base de Datos";
$opi_reco ="Opiniones y/o Recomendaciones";
$oper ='OPERACIONES';
$O ='O';
$of1 =' del Administrador del Sitio Web';
$of2 =' a donde se enviaran los E-Mails';
$opera = 'Operador L&oacute;gico para todos los campos';
$ordenapor = "Ordenar por";
$organ1 = "Ordenar por Clave";
$obser = "Observaci&oacute;n";
$in_cont="Nuevo concepto";
$Oculto="Oculto";

//P
$Para ='Para';
$puede ='<br>Usted puede ';
$puede11 =" Usted puede ";
$puede1 ='A&ntilde;adir</a> un nuevo registro';
$page1 ='P&aacute;ginas';
$pagge ='P&Aacute;GINA';
$pagge1 ='P&aacute;gina ';
$pagge2 ='Ir a la ';
$person ="Onom&aacute;stico";
$pais ='Pais ';
$prod ='Productor';
$pclave ='Escriba una palabra que recuerde su Contrase&ntilde;a (Opcional)';
$pass ='Contrase&ntilde;a';
$pass2 ='Las Claves no coinciden';
$pass3 ='repetir la Clave';
$pass1 ='Clave';
$pass4 ='Registro de Claves';
$pass5 ='Claves de Softwares';
$plantilla = "Plantillas";
$prin = "Imprimir";
$plea = "Por favor es necesario el campo: ";
$plea0 = "Por favor seleccione la, o las Entidades que desea fusionar";
$plea1 = "Por favor seleccione el, o los registros que desea ";
$plea2 = "Por favor debe escribir";
$plea10 = "Por favor debe escribir el criterio de B&uacute;squeda";
$plea7 ='Por favor revise los permisos de Lectura/Escritura de &Eacute;ste.';
$plea3 = "el Cuerpo de su Correo";
$plea4 = "el Asunto de su Correo";
$plea5 = "Por favor emita su criterio";
$plea6 = "No, por favor verifique si est&aacute; instalado y corriendo el Servidor MySql";
$plea8 = "Por favor seleccione el ";
$plea9 = "Por favor de Click en este Link o copielo en su Navegador para activar su cuenta: ";
$Por ="Por";
$Por1 =" por ";
$param ='Son esos los parametros correctos? El Software creara las tablas necesariasintentara ahora llenar la base de datos usando los parametros que usted ha facilitado';
$pos_inf ="Informaci&oacute;n Post-Instalaci&oacute;n de la Base de Datos";
$pos_inf1 ="Advertencia en la Creaci&oacute;n de la Base de Datos";
$privile1 ='Usted no tiene suficientes privilegios. Solo el Administrador del Sitio Web tiene acceso a este M&oacute;dulo';
$provincia="Provincia";

//Q
$quit = "Quitar Referencia";
$quit1 = "Quitar Im&aacute;n";
$quit2 = "Quitar Logo";
$que ='&iquest;Qu&eacute; desea Exportar?';
$que1 ='La Base de Datos ha sido Salvada';
$quecoin ='que tegan coincidencia con ';

//R
$btResponsable="Responsable del Medio";
$rbusqueda ='RESULTADO DE LA B&Uacute;SQUEDA ';
$r ='Regular';
$responder ='Responder';
$red = "Red de Archivos";
$retor = 'Retornar';
$retor_to = 'Retornar a la p&aacute;gina anterior';
$redig = "Referencia Digital";
$n_redig = "Nueva Referencia Digital";
$requiere = "Se requiere un valor para ";
$res_bus ="Para restringir m&aacute;s su b&uacute;squeda, seleccione una Materia";
$remember = "Por favor recuerde que el Articulo debe relacionarse a los temas del trabajo en los Archivos.";
$remember1 = "El Articulo debe estar relacionarse a los temas del trabajo en los Archivos,\nla Divulgacion de estos, la Conservacion, la Gestion Documental, etc.";
$remember2 ='Por favor seleccione otro Titulo, ya ';
$remember3 = '\n se encuentra registrado por Usted';
$restring  = "Usuario Restringido";
$restring1 ='Restringido (S&oacute;lo Consulta)';
$registr1 = "Primer Registro";
$registr2 = "Siguiente Registro";
$registr3 = "Registro Anterior";
$registr4 = "&Uacute;ltimo Registro";
$registr5 = "Registro";
$rgla = "Regla";
$recuerdo = "Le recordamos que el Titulo, el Codigo, la Fecha, Nivel de Descripcion y el Contenido o Resumen, son imprescindibles";
$recog = "Recoger";
$right1 = "<a href='gpl.html' target='_blank'>Licencia GNU/GPL</a>.";
$rutax = "Ruta de guardado de Configuraci&oacute;n";
$rutax1 = "Ruta de guardado de sesiones";
$rutax2 ='Ruta fisica del Sitio';
$rutax3 ='Ruta virtual o URL del Sitio Web';
$rout ='Ruta';
$reg_nArch =', Usted debe Registrar un Archivo';
$reemplazz = 'Reemplazar';
$realmente = 'Realmente desea hacerlo?';
$repite_campo = "Repetir el contenido del Campo";
$cantielimia ="Cantidad a Eliminar: ";
//S
$sistema ='Red de Archivos de la Rep&uacute;blica de Cuba.';
$serie1 ='Serie';
$strsearch ='Buscar';
$sololeido ='solo en Correos Le&iacute;dos.';
$soporte ='Soporte';
$strOK = 'Aceptar';
$stsql ='para crear el fichero compactado SQL';
$stmodificar ='Modificar';
$steliminar1 ='Eliminar';
$steliminar2 ='para Crear el fichero PDF';
$stnuevo ='Nuevo Registro';
$stnuevoart = 'Nuevo Art&iacute;culo';
$suopinion ='EMITA SU OPINI&Oacute;N';
$sugerirportal ='Sugerir Portal';
$sugerirportal1 ='Sugerir';
$sugerirportal2 ='</a> este portal a un amigo.</div><br>';
$sugerencia ='Te recomiendo que visites este Portal.';
$siteadmin ='Administradores de Sitios';
$siteadmin1 ='Administrador del Sitio Web';
$siteadmin2 ='Super Administrador';
$strError = 'Error';
$subcrib ='SUSCRIBIRSE';
$strerror = 'Mensaje de error';
$strerror2 ="Se han producido algunos errores al a&ntilde;adir datos en la  base de datos!. No puedes continuar con la instalaci&oacute;n.";
$strerror3 = "Usted no ha solicitado una Llave de Descarga o la Llave que introdujo no es correcta";
$strerror4 = "Su credito se ha agotado";
$strinsert ="Mensaje de Inserci&oacute;n";
$strserach = "Mensaje de B&uacute;squeda";
$strinforma ='Mensaje de Informaci&oacute;n';
$strerlimina ='Mensaje de Eliminaci&oacute;n';
$strmodifica ='Mensaje de Modificaci&oacute;n';
$soloselec ='Solo seleccionar a un Remitente para responderle';
$strAccessDenied = 'Acceso denegado...';
$strproceso ="Proceso de Registro";
$solodocu ='Usted s&oacute;lo puede editar Documentos.';
$solodocu1 ='Usted s&oacute;lo puede editar Documentos pertenecientes a su archivo.';
$solodocu2 ='Usted s&oacute;lo puede eliminar Documentos pertenecientes a su archivo.';
$strnousuario = 'El Usuario y/o Contrase\u00F1a no son correctos';
$selectn_nivel = "Seleccione uno si lo va a cambiar";
$selectpais ='Seleccione un Pais';
$selectprov ='Seleccione la Provincia';
$selectmot = 'Motivo';
$selectusr = 'Seleccione el Tipo de Usuario';
$selectusr1 = 'Seleccione el Usuario';
$selectmateria = 'Seleccione una Materia';
$selectBD ='Seleccione la Base de Datos';
$selectDB0 =' la Tabla que va a Importar';
$selectBD1 ='Seleccione de la Base de Datos ';
$selectDB2 ='la Tabla que va a Exportar';
$selectDB4 ='las Tablas que va a Exportar';
$selectBD3 ='la o las Tablas que va a exportar';
$selecttable ='Seleccione de la Tabla';
$selectscript ='Por favor, seleccione el o los fichero(s) que desea importar';
$selectscript1 ='Por favor, seleccione la(s) Tabla(s) que desea Exportar';
$sumary = 'Resumen por Meses';
$sumary1 = 'Resumen por A&ntilde;os';
$sumary2 = 'Resumen por D&iacute;as';
$seguro ='Usted est&aacute; a pundo de eliminar uno o m&aacute;s registros, de hacerlo se perder&aacute;n los datos y no podr&aacute; recuperarlos.<br>&iquest;Desea continuar?.';
$seguro1 = "Son esos los datos correctos?";
$seguro2 = "Si lo hace, se perderan los datos y no podra recuperarlos. Desea continuar?";
$seguro3 ="Con esta acci&oacute;n se reemplazar&aacute; la actual Base de Datos por la Estructura solamente.";
$seguro4 ="Con esta acci&oacute;n se reemplazar&aacute;n los datos existentes. Desea continuar?";
$sel_all = 'Marcar todos';
$des_all = 'Desmarcar todos';
$sav_prin = 'Guardar/Imprimir';
$sav_prin1 = "GUARDAR O IMPRIMIR RESULTADO";
$sav_prin2 = "GUARDAR RESULTADO";
$sav_prin3 = 'Guardar';
$servi = "SERVIR";
$su_em = "su E-Mail";
$sel_si = "Seleccione uno si lo va a modificar";
$sav_print = "Imprimir";
$s_email = "ENVIAR CORREO";
$s_n = "(s/n)";
$scri_imp = "Script importado";
$scri_imp0 = "Los datos de las tablas";
$scri_imp1 = "Los datos de la tabla ";
$scri_imp2 =" perteneciente a la Base de datos " ;
$scri_imp21 =" pertenecientes a la Base de datos " ;
$scri_imp3 =" se han exportado.";
$scri_exp = "La Base de Datos ";
$scri_exp1 = ", se ha exportado.";
$save_all ="GUARDAR O IMPRIMIR LA CONSULTA DE TODOS LOS REGISTROS ENCONTRADOS";
$s_fon ="Sub-Fondo";
$s_fon1 ="Fondo";
$solo_doc =", Usted solo puede editar Documentos";
$serv1 ="Servidor SMTP";
$sigui = "Siguiente";
$s_corre ='Si la URL y la Ruta F&iacute;sica son las correctas no las cambies. Si no est&aacute;s seguro pregunta a tu ISP o Administrador para asegurarte. En la gran mayor&iacute;a de los casos los valores que muestra el instalador Web son los correctos.';
$sol_registr ='Solicitud de Registro a favor de';
$sol_registr0 ='Solicitud de Registro';
$sol_registr3 ='Solicitud de Clave';
$sol_registr1 ='Su Solicitud ha sido enviada. Por favor revise su Correo';
$sol_registr2 ='Su Solicitud no ha sido enviada. Revise la su conexion';
$sol_registr4 ='Recordatorio de Solicitud de Registro';
$systema = '- Red de Archivos en la Provincia Granma -';
$sist_op ='SISTEMA OPERATIVO';
$suceso ='Suceso';
$solo_num ="S&oacute;lo N&uacute;meros";

//T
$Tex ='Texto';
$totalusuario ='Total de Usuarios registrados';
$totalusuario1 ='Total de Usuarios';
$totalusuario2="Usuarios registrados";
$title_new ='Crear una cuenta de usuario';
$totalrecord ='Total de Registros';
$totalrecord1 ='Registro del ';
$totalrecord2 =' de un total de ';
$totalrecord3 =' al ';
$title ='T&iacute;tulo';
$title2 ='Titulo';
$title3 ='T&Iacute;TULO';
$title1 = "Sub-T&iacute;tulo";
$totalopinion ='Total de Opiniones';
$tienenuevo ='En estos momentos Ud. tiene <b>';
$tutienes="Usted tiene <font color='red'><b>";
$tienenuevo1 ='</b></font> mensajes sin leer';
$tienenuevo2 ='</b></font> mensaje sin leer';
$tienenuevo3 =', y otros en Correos Le&iacute;dos.';
$tarde ='Buenas tardes ';
$today =' hoy es';
$tele ='Tel&eacute;fono(s)';
$t_materia = "T&eacute;rmino de la Materia";
$t_usuario = "Tipo de Usuario";
$t_usuario1 = "T. Usuario";
$t_ayuda ="TEMAS DE AYUDA DE ";
$t_rfd = "Tama&ntilde;o";
$tranfer ='Transferencia';
$tma ='Tema';
$tamao_fi ='El fichero que Usted esea importar es demasiado grande. Por favor verifique las tablas que m&aacute;s datos tengan e imp&oacute;rtelas por separado.';
$tipo_fich ='<b>Nota:</b> El fichero a importar puede ser:&nbsp;&nbsp;<b>.SQL</b>&nbsp;&nbsp;o&nbsp;&nbsp;<b>.ZIP</b>.';
$tipo_fich1 = " Debe tener en cuenta adem&aacute;s, que este fichero debe contener solamente datos de la tabla seleccionada, no puede contener estructura de esta tabla ni de otra.";
$type_q ='Tipo de Consulta: ';
$tb_bd ='Tablas de la Base de Datos';
$tblass ='Tabla';
$terminos   = '<a href="#modal3">T&eacute;rminos de Uso<?php echo $click1.strtolower($sho).$bddatosper;?><a>';
$term='T&eacute;rminos de Uso';
$cversiones='Control de Versiones';
$textoam='Este sitio web ha sido concebido en aras de contribuir al Control eficiente de las Tecnolog&iacute;as de la Inform&aacute;tica y las 
Comunicaciones. Su distribuci&oacute;n es totalmente gratuita, significando adem&aacute;s que toda sugerencia u opini&oacute;n ser&aacute siempre
bien recibida en pos de su mejora y funcionamiento eficaz. <br><hr><b>Datos de los Autores</b><br><hr>
<a href="mailto:manuel.jesus@zetifmf.azcuba.cu"><b>Ing. </b>Manuel de Jes&uacute;s N&uacute;&ntilde;ez Guerra</a><br>
Especialista en Ciencias Inform&aacute;ticas<br> Empresa de Servicios T&eacute;cnicos Industriales (ZETI), <br> UEB F&aacute;brica  Manuel Fajardo<br>
GRUPO AZCUBA<br> 
sita en Ave. Paquito Rosales, Km. 1, Manzanillo, Granma. <br>


<b>Tel&eacute;fonos:</b><br>
(0123) 57 7198<br>
(53)   53924528<br>
<hr>
<a href="mailto:carlos.pollan@gtm.jovenclub.cu"><b>Msc.</b> Carlos Poll&aacute;n Estrada</a><br>
Inform&aacute;tico en: Joven Club de Computaci&oacute;n<br>
sita en Municipio Guant&aacute;namo,<br>
Provincia Guant&aacute;namo. <br>

<b>Tel&eacute;fonos:</b><br>

(53)   58222269<hr>';

//U
$ubica ="Ubicaci&oacute;n/Signatura";
$user_con ='Usuarios Online';
$user_proceso ='Usted no ha completado el proceso de Registro.<br>Por favor revice su Mensajer&iacute;a o p&oacute;ngase en contacto con el ';
$user_proceso1 ='Este mensaje es para confirmarle que ya Usted es Usuario de nuestro Portal Web. Estos sus datos generales:';
$user_proceso2 ='Esperamos que encuentre la informacion que busca. Si tiene alguna inquietud o sugerencia, por favor no dude en contactarnos.';
$useract ='Usuario';
$usuari ='Usuarios (Solo Consulta)';
$useradvan ='Usuarios Avanzados';
$usuar = "Usuarios";
$upgrade = 'Actualizar';
$hist_upgrade = "Historial de Modernizaciones";
$u_rel ="Unidades Relacionadas";
$u_mente ="Usualmente -localhost-";
$unidad = 'Unidad'; 

//V
$v_ficha = "Ver";
$SQLversion="Versi&oacute;n del servidor MySQL";

//W
$wrote ='escribi&oacute;';
$web ='Sitio Web';
$way_in = "Forma de Ingreso";
$w_site = "Sitio web";
$web_name = "Nombre del Portal";
$web_name1 = "URL Soporte T&eacute;cnico. Ayuda";

//Y
$Y = "Y";
$year = "A&ntilde;o";
$ya_esta = " ya esta Registrado, por favor escoja otro";
$ya_esta3 = ' ya est&aacute; conectado. <a href="#desconn">Desconectar</a>';
$yes1 ="Si";


///
$Umes = "Un Mes";
$Dmes = "Dos Meses";
$Tmes = "Tres Meses";
$enque = "palabras que contienen: ";
$enque1 = "palabras que comienzan con: ";
$enque2 = "palabras que terminan en: ";
$enque3 = "palabras iguales a: ";
$enque4 = "palabras distintas a: ";
$Dicc = "Breve Diccionario de la lengua espa&ntilde;ola";
$Dicc1="Diccionario";
$Sho="Mostrar";

$Concepto="Concepto";
$mardesm="Marcar/Desmarcar Todos";
$mardesm1="Marcar/Desmarcar/Invertir Selecci&oacute;n";
$cade=" para la cadena: ";
$Go="Ver";
$Registrosdel = "Registros del";
$DEL =" del ";
$dir2 = "Directorio Temporal del Servidor";
$Predeterminado ="Prdeterminado";
$Self ="Misma Ventana";
$Top ="Ventana Principal";
$Blank ="Nueva Ventana";
$Parent ="Ventana Padre";
$crea_pag ="Crear P&aacute;gina: ";
$crea_pag1 ="Modificar P&aacute;gina: ";
$exptr ='Exportar';
$exptr1 ='Exportando';
$exptr2 ='Comprimiendo';
$exptr3 ="Eliminando Ficheros Temporales";
$exptr4 ="Eliminando ";
$exptr5 ='Descomprimiendo';
$ficher = "Fichero";
$ficher1 = "Fichero Dictamen";
$ejecutando="Ejecutando Script";
$strproceso5 ="La Importaci&oacute;n ha Terminado. Tiempo de Ejecuci&oacute;n: ";
$strproceso ="Procesos en el Servidor MySQL";
$strproceso1 ="Procesos";
$strproceso2 ="La Exportaci&oacute;n ha Terminado. Tiempo de Ejecuci&oacute;n: ";
$strproceso3 = " Seg";
$strproceso4 = " Min";
$strproceso5 ="La Importaci&oacute;n ha Terminado. Tiempo de Ejecuci&oacute;n: ";
$scri_imp = "Script importado";
$scri_imp0 = "Los datos de las tablas";
$scri_imp1 = "Los datos de la tabla ";
$scri_imp2 =" perteneciente a la Base de datos " ;
$scri_imp21 =" pertenecientes a la Base de datos " ;
$scri_imp3 =" se han exportado.";
$scri_imp4 ="Analizando Script";
$scri_imp5 = "Los datos han sido importado a la Base de Datos <b>-%s-</b>";
$scri_exp = "La Base de Datos ";
$scri_exp1 = ", se ha exportado.";
$scri_exp2 = "Exportado";
$scri_exp3 = "Importado";
$descarg ="Ver/Descargar fichero ";
$proceso1 = "Error de ejecusi&oacute;n: ";
$proceso = "Proceso interrumpido";
$enlinea = " Registrados";
$enlinea1 = " Registradas";
$enlinea2 = " Agregadas";
$enlinea3=" en Historial";
$enlinea4=" en tr&aacute;mite de ";


//CONSULTA
$esigual ="IGUAL A";
$noigual ="NO ES IGUAL";
$mayorque ="MAYOR QUE";
$mayorigual ="MAYOR E IGUAL";
$menorque ="MENOR QUE";
$menorigual ="MENOR E IGUAL";
$esnulo ="ES NULO";
$noesnulo ="NO ES NULO";
$contiene ="CONTIENE";
$comienzacon ="COMIENZA CON";
$terminacon ="TERMINA CON";
$optiones="Opciones";
$seleccione="Seleccione ";
$dela = " de la ";
$dela1 = " de la ";
$dela2 = " de las ";
$dela3 = " de la ";
$tablasa="Tabla";
$copiando = "Copiando ";
$click1 ="Click para ";
$sho="Mostrar";
$subfi="Fichero a subir:";
$paingresar="Click para Iniciar/Terminar Secci&oacute;n...";
$have="Tienes ";
$perfile="Perfiles";
$El = " el ";
$permisos="Permisos";
$nomens="Usted no no tiene permisos para evnviar mensajes, por favor p&oacute;ngase en contacto con el Administrador.";
$nomens1="Este Usuario no puede recibir Mensajes.";
$nomens2="Usted no puede Enviar Mensajes.";
$Adjunto="Adjunto";
$Grupos="Grupos";
$envirec="Enviar/Recibir";
$p_proh="palabras Censuradas";
$ser_web="Servicios Web";
$admini="Administrador";
$Sexo = "Sexo";
$Edad="Edad";
$quitado="Usted ha sido eliminado de este Sitio Web, por favor p&oacute;ngase en contacto con el Administrador si tiene alguna duda.";
$Consultas ="Consultas";
$publicacio="Publicaciones";
$quemas="Usuarios Asiduos";
$temaidioma="Configuraci&oacute;n de su Idioma y Tema";
$opisitio="Opini&oacute;n sobre el Sitio";
$imagenes="Im&aacute;genes";
$Dayis = 'D&iacute;as';
$SI="Si";
$btConsecu="Corresponde el consecutivo";
$collat = "Cotejamiento";
$nulo= "Nulo";
$llave = "Llave";
$campos_para3 ='Long/Val';
$btvapr="V. Pred.";
$fina = "Al comienzo de la tabla";
$fina1 = "Al final de la tabla";
$fina2 = "Despu&eacute;s de ";
$wellc="Bienvenido a REGIMED";
$wellc1="Registro de Medios Inform&aacute;ticos. Software multiplataforma para el control de las tecnologias de la informaci&oacute;n";
$tareas="Tareas Pendientes";
$rden = "Orden";
$btopcion="Opciones";
$stregistro="Registro de ";
$Asunto ="Asunto";
$Cuerpo="Cuerpo";
$SU=" su ";
$noarea="Ya existe un &Aacute;rea con ese nombre";
$noareac="Ya existe una Categor&iacute;a con ese nombre";
$catmod="Categor&iacute;a a Modificar";
$catmod1="Categor&iacute;as a Modificar";
$nomnewcat=" el nombre de la nueva Categor&iacute;a";
$elimino="El fichero -%s-, ha sido eliminado";
$Eliminasalva="Eliminate File of Save";
$preinstall ="Chequeo de Pre-instalalaci&oacute;n.";
$paso ="Paso";
$licence ="Licencia";
$comprob = "Comprobar otra vez";
$texto1="Si alguno de estos elementos aparece resaltado en rojo, debe tomar las medidas oportunas para corregirlo. Caso contrario el sitio podr&iacute;a no funcionar correctamente. ";
$texto2="A continuaci&oacute;n mostramos los ajustes recomendados de PHP para asegurar la plena compatibilidad con el sitio! el sitio funcionar&aacute;  si tu configuraci&oacute;n no se ajusta exactamente con estas recomendaciones, no obstante, alguna utilidad de elste sitio puede dejar de ser operativa por dichos cambios. ";
$footer="RegiMed! es un Software Libre concebido bajo licencia a GNU/GPL. ";
$btmantenimientos=" planificados";
$confsql="Configuraci&oacute;n de la Base de Datos MySQL";
$btpuede="Ud., puede comenzar a usar este sitio Web despu&eacute;s de 4 simples pasos.";
$btdatosentidad5="Nombre de la Entidad";
$btCodigo="C&oacute;digo";
$btCodigo1="C&oacute;digo REUP";
$perteneciente="Perteneciente al Sector";
$perteneciente1="Sector al que Pertenece";
$Web ='Sitio Web';
$btOpcional="Opcional";
$btprovincia="Provincia";
$hint="Estos no son indispensables, pero si necesario por razones de Seguridad";
$errorcon="Error de Conexi&oacute;n. Por favor";
$errorcon1="Error de Conexi&oacute;n. Por favor verifique los datos";
$btverifique="verifique</a> Servidor, Usuario y Contrase&ntilde;a.";
$btadvierte="Si Reemplaza, se perder&aacute; toda la informaci&oacute;n. Si Conecta, la nueva Base de Datos se ajustar&aacute; a la nueva versi&oacute;n sin peder ning&uacute;n Dato";
$yaExiste =" ya existe";
$btdesea="Qu&eacute; desea hacer";
$conectarr = "Conectar";
$btconexcion ="La conexi&oacute;n a la Base de Datos";
$btestablecido="se ha establecido satisfactoriamente";
$ServidorMySQL="Servidor MySQL";
$UsuarioMySQL="Usuario MySQL";
$btfinalizar="Terminar";
//d�as
$lunes =" Lunes";
$mart =" Martes";
$mierc =" Mi&eacute;rcoles";
$juev =" Jueves";
$vier =" Viernes";
$sab =" S&aacute;bado";
$dom =" Domingo";
//meses
$ene =" Enero";
$feb =" Febrero";
$mar =" Marzo";
$abr =" Abril";
$may =" Mayo";
$jun =" Junio";
$jul =" Julio";
$ago =" Agosto";
$sep =" Septiembre";
$oct =" Octubre";
$nov =" Noviembre";
$dic =" Diciembre";
$soncorrector="RegiMed intentara llenar la Base de Datos con la informacion que usted ha facilitado, son estos correcto?";
$btfusionar="Fusionar Unidad";
$btfusionar1="Fusionar";
$btfusionar2="Entidades a Fusionar";
$nomajax="Nombre de la Base de Datos que va a utilizar para este Software";
$noborrar = "El Usuario seleccionado no puede ser Eliminado por ser el Administrador del Sitio Web";
$bttotraspaso=" para realizar Traspazos";
$bttotraspaso1=" para realizar Mantenimientos";
$bttotraspaso2=" para realizar Reparaciones";
$noimportar = "La Unidad que intenta recepcionar tiene menos Categor&iacute;as de Medios que las existentes";
$nometearea="El &Aacute;rea que intenta a&ntilde;adir ya existe, por favor seleccione otro nombre.";
$componentes ="Por componentes";
$verdetalles="ver detalles";
$verdetalles1="Ver Expediente: ";
$coincidencia="Coincidencias: ";
$btMOTIVOS="MOTIVOS";
$btcreditos="CR&Eacute;DITOS";
$btcreditos1="Cr&eacute;ditos";
$seconcto=", se ha conectado";
$seconcto1=", se ha desconectado";
$btestesitio=" a este Sitio Web";
$desconocida="Pa&iacute;s no Registrado";
$bddatosper=" datos personales del Autor...";
$btenred="En Red";
$btConectividad="Conexi&oacute;n";
$btenuso="En Uso";
$btrotas="Rotas";
$btPBajas="P. Bajas";
$btotrotras="Realizar otro Traspazo";
$btotrotras1="Realizar Traspazo";
$btmostrarall="Todas las Categor&iacute;a de Medios";
$btmostrarmon="Mostrar todos los Monitores";
$btmon="Monitores";
$btmostraresc="Mostrar todas las Fotocopiadoras y/o Escanner";
$btesc="Escanner";
$btmostrarimp="Mostrar todas las Impresoras";
$btimp="Impresoras";
$btmostrarpc="Mostrar todas las Computadoras";
$btpc="Computadoras";
$btlista = "Listado de Medios";
$btentramite = "Listado de Medios en proceso de baja";
$Reincorporar="Reincorporar";
$Reincorporar1="Retornar al &Aacute;rea de origen";
$btREGISTROTRASPASOS="REGISTRO DE TRASPASOS";
$btRealizarSalvar = "Realizar Salvas";
$btEnviarEMail="Enviar E-Mail";
$btGuardadBusqueda="Guardar B&uacute;squeda";
$btmostrarall0="Total de Categor&iacute;a de Medios";
$pass0 ='Total de Registro de Claves';
$btpmtto0 = 'Total de Mantenimientos';
$btEXPEDIENTE0="Total de Expedientes";
$btTAreas="Total de &Aacute;reas";
$btregmedio0='Total de Registro de Medios';
$btResoluciones0 ='Total de Resoluciones';
$btAreas0='Total de &Aacute;REAS';
$new0 ='Total de Usuarios';
$btprep0 = 'Total de Reparaciones';
$bttotraspaso0 = 'Total de Traspasos';
$btbajas0 = 'Total de Bajas';
$btinsp0 = ' Total de Inspecciones';
$btListado0="Total de Medios Defectuosos";
$bteditaunid0='Registro de Incidencias';
$Incidencias='Incidencias';
$seguro0 ='Usted est&aacute; a pundo de eliminar un registro, de hacerlo se perder&aacute;n los datos y no podr&aacute; recuperarlos.<br><b>&iquest;Desea continuar?</b>.';
$btmedios ="Medios";
$yaexiste1 = "Ya existe la entidad <font color='#000000'>%s</font> con el codigo ";
$upgrade0 = "Desea Actualizarla?";
$registroclave="Nuevo Registro";
$btclose="Cerrar";
$btconectado = "Conectado(s):";
$btversi ="Versi&oacute;n";
// Control de Cambios
$a1="Rediseño del software para el trabajo multi-unidad. ";
$a2="Utilizaci&oacute;n de bootsrap 3.0, empleo de CSS3 y HTML5.. ";
$a3="Solucionado bug a la hora de crear la tabla <b>'conectado'</b>. ";
$a4=" Empleo del motor InnoDB y redise&ntilde;o de la Base de Datos. ";
$a5="Reprogramaci&oacute;n para la actualizaci&oacute;n de la estructura de Base de Datos, 
        garantizando la integridad  de los datos de aquellos usuarios que ya 
        ten&iacute;an la aplicaci&oacute;n en explotaci&oacute;n.  ";
$a6="Reconsiderado el acceso al sitio por 'usuarios' adem&aacute;s del 'invitado', tal como fuera
        &nbsp;&nbsp;concebido desde la versi&oacute;n inicial, pero deshechado en la v2.1 ";
$a7="Implementaci&oacute;n de una soluci&oacute;n para 'desconectar' a los usuarios que al cerrar el
        navegador consciente o inconscientemente, sus sessiones quedaban registradas en 
        la base de datos y por consiguiente no pod&iacute;an logearse nuevamente.";		
$a8=" Empleo de Men&uacute;es Popup y ventanas Modales para hacer m&aacute;s amigable su operacionalidad";
$a9="La lista de &oacute;rganos emisores de las resoluciones, se nutre del propio usuario. ";
$a10="Adem&aacute;s del m&oacute;dulo 'traspasos', se implementa nueva caracter&iacute;stica para que un Custodio 
        transfiera uno, varios o todos sus medios (aft) para otro u otros Custodios.";
$a11="Aspectos de Apariencia.";
$a12="El presente manual de usuario, ha sido concebido para lograr un eficaz funcionamiento de este sitio. A continuación se relaciona una lista con los primeros pasos a seguir:";
$a13="Sustituci&oacute;n de funciones obsoletas para la actual versi&oacute;n 7.x de Php.";
$a14="Se insertan 2 nuevos m&oacute;dulos: Sellos y Registro de Claves de Software.";
$a15="Se adec&uacute;a el Plan de Mantenimiento para registrar el gasto en valores para cuando el Mantenimiento corre a cuentas de terceros.";
$a15a="Se modifican aspectos relacionados con roles de usuarios.";
$a17="Se sustituyen los ficheros como medios de almacenamiento en historial de bajas y modernizaciones.";
$a18="Se ampl&iacute;an los detalles de componentes en el Expediente T&eacute;cnico.";
$bajassd="Bajas sin Dictamen T&eacute;cnico.";
$ressin="Resoluciones sin Referencia.";
$sigueme = "S&iacute;gueme...";
$ejecuor ="Ejecutante";
$espreciso ="Es preciso generar un nuevo tal&oacute;n de Sellos.";
$yanoexiste = "Este AFT ya no figura en los inventarios.";
?>